export const Images = {
  ShwraLogo: "/assets/Icons/Logo.svg",
  MobileShwraLogo: "/assets/Icons/mobileShwraLogo.svg",
  ToggelButton: "/assets/icons/Hamburger.svg",
  Global: "/assets/Icons/global.svg",
  toggle: "/assets/navbar/toggle.svg",
  responsiveLogo: "/assets/navbar/responiveLogo.svg",
  ShwraBrownLogo: "/assets/Icons/brownLogo.svg",
  contract_review: "/assets/Icons/contract-review.svg",
  contract_drafting: "/assets/Icons/contract-drafting.svg",
  law: "/assets/Icons/law.svg",
  background_triangle: "/assets/Icons/background_triangle.svg",
  graph: "/assets/Icons/graph.svg",
  pie_chart: "/assets/Icons/pie-chart.svg",
  check: "/assets/Icons/checked.svg",
  uncheck: "/assets/Icons/inActive.svg",
  riyal: "/assets/Icons/Riyal.svg",
  musheer_interface: "/assets/Icons/musheer-interface.svg",
  musheer_interface2: "/assets/Icons/musheer_interface2.png",
  musheer_interface_border: "/assets/Icons/musheer-interface-border.png",
  Phone: "/assets/Icons/FooterIcons/phone.png",
  Email: "/assets/Icons/FooterIcons/emails.png",
  Twitter: "/assets/Icons/FooterIcons/twitter.png",
  Linkdin: "/assets/Icons/FooterIcons/link.png",
  FaceBook: "/assets/Icons/FooterIcons/fb.png",
  Insta: "/assets/Icons/FooterIcons/insta.png",
  Whatsapp: "/assets/Icons/FooterIcons/Whatsapp.png",
  TikTok: "/assets/Icons/FooterIcons/TikTok.png",
  shwra_ai: "/assets/Icons/shwra_ai.svg",
  search_engine: "/assets/Icons/search_engine.png",
  contract_review_interface: "/assets/Icons/contract_review.png",
  summerization: "/assets/Icons/summerization.png",
  case_study: "/assets/Icons/case_study.png",
  translation: "/assets/Icons/translation.png",
  drafting_doc: "/assets/Icons/drafting_doc.png",
  analyze: "/assets/Icons/analyze.png",
  summerization2: "/assets/Icons/summerization2.png",
  saas: "/assets/Icons/saas.png",
  musheer_service: "/assets/Icons/service/musheer_service.svg",
  saas_service: "/assets/Icons/service/saas_service.svg",
  summerization_service: "/assets/Icons/service/summerization_service.svg",
  document_review_service: "/assets/Icons/service/document_review_service.svg",
  document_drafting_service:
    "/assets/Icons/service/document_drafting_service.svg",
  translation_service: "/assets/Icons/service/translation_service.svg",
  case_study_service: "/assets/Icons/service/case_study_service.svg",
  contract_review_service: "/assets/Icons/service/contract_review_service.svg",
  contract_drafting_service:
    "/assets/Icons/service/contract_drafting_service.svg",
  search_engine_service: "/assets/Icons/service/search_engine_service.svg",
  heroBackground: "/assets/Icons/heroBackground.png",
  EmailNew: "/assets/Icons/FooterIcons/Email.png",
  Abdualaziz_aldakheel: "/assets/Icons/Team/Abdualaziz_aldakheel.webp",
  Abdullah_Alamri: "/assets/Icons/Team/Abdullah_Alamri.webp",
  Mohammad_Aldakheel: "/assets/Icons/Team/Mohammad_Aldakheel.webp",
  Saleh_alassaf: "/assets/Icons/Team/Saleh_alassaf.webp",
  Dhaif_Allah: "/assets/Icons/Team/Dhaif_Allah.webp",
  shwra_black: "/assets/Icons/shwra_black_logo.svg",
  black_globe: "/assets/Icons/globe.svg",
  Avatargroup: "/assets/Icons/Avatargroup.svg",
  copy: "/assets/Icons/copy.svg",

  caseStudyService: "/assets/services/caseStudy.png",
  contractReviewService: "/assets/services/contractReview.png",
  documentDraftingService: "/assets/services/documentDrafting.png",
  documentReviewService: "/assets/services/documentReview.png",
  documentReview2Service: "/assets/services/documentReview2.png",
  legalSaasService: "/assets/services/legalSaas.png",
  legalTransaltionService: "/assets/services/legalTransaltion.png",
  legalSummarizationService: "/assets/services/legalSummarization.png",
  searchEngineService: "/assets/services/search.png",
  shwraFav: "/favIcon.svg",
  musheerServices: "/assets/services/musheer.png",

  // webp
  caseStudyServiceWebp: "/assets/services_optimized/caseStudy.webp",
  contractReviewServiceWebp: "/assets/services_optimized/contractReview.webp",
  documentDraftingServiceWebp:
    "/assets/services_optimized/documentDrafting.webp",
  documentReviewServiceWebp: "/assets/services_optimized/documentReview.webp",
  documentReview2ServiceWebp: "/assets/services_optimized/documentReview2.webp",
  legalSaasServiceWebp: "/assets/services_optimized/legalSaas.webp",
  legalTransaltionServiceWebp:
    "/assets/services_optimized/legalTransaltion.webp",
  legalSummarizationServiceWebp:
    "/assets/services_optimized/legalSummarization.webp",
  searchEngineServiceWebp: "/assets/services_optimized/search.webp",
  musheerServicesWebp: "/assets/services_optimized/musheer.webp",
  contractDraftingServicesWebp:
    "/assets/services_optimized/contractDraftingServicesWebp.webp",
};
